# Data Preprocessing

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.11.0'

In [3]:
dataset= pd.read_csv("Churn_Modelling.csv")

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [9]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [1])], remainder="passthrough")
x=np.array(ct.fit_transform(x))

In [11]:
x[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
x_train  

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

# Building ANN

## Initializing the ANN

In [15]:
ann=tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

## Adding second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

## Adding output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Training ANN

## Compiling ANN

In [19]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

## Training ANN

In [20]:
ann.fit(x_train, y_train,batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 3ms/step - loss: 0.6279 - accuracy: 0.6450
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4877 - accuracy: 0.7970
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4451 - accuracy: 0.8064
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4267 - accuracy: 0.8159
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4189 - accuracy: 0.8196
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4115 - accuracy: 0.8254
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4024 - accuracy: 0.8322
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3924 - accuracy: 0.8340
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3835 - accuracy: 0.8379
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3757 - accura

250/250 [==============================] - 1s 4ms/step - loss: 0.3319 - accuracy: 0.8644
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3313 - accuracy: 0.8649
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8637
Epoch 84/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3318 - accuracy: 0.8639
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3318 - accuracy: 0.8636
Epoch 86/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3315 - accuracy: 0.8639
Epoch 87/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3314 - accuracy: 0.8652
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8645
Epoch 89/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3312 - accuracy: 0.8636
Epoch 90/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3317 - accuracy: 